/**
 * Tests for SVGExporter
 * Validates SVG extraction, metadata injection, and optimization
 */

import { describe, it, expect, beforeEach } from '@jest/globals';
import { SVGExporter } from '../../artifacts/export/SVGExporter.js';

describe('SVGExporter', () => {
  let exporter: SVGExporter;
  
  beforeEach(() => {
    exporter = new SVGExporter();
  });
  
  describe('SVG Extraction', () => {
    it('should extract SVG from HTML', () => {
      const html = '<html><body><svg width="100" height="100"></svg></body></html>';
      const svg = exporter.extractSVG(html);
      
      expect(svg).toContain('<svg');
      expect(svg).toContain('</svg>');
    });
    
    it('should extract SVG with nested elements', () => {
      const html = '<html><svg><g><circle r="10"/></g></svg></html>';
      const svg = exporter.extractSVG(html);
      
      expect(svg).toContain('<g>');
      expect(svg).toContain('<circle');
    });
    
    it('should return null if no SVG found', () => {
      const html = '<html><body><div>No SVG here</div></body></html>';
      const svg = exporter.extractSVG(html);
      
      expect(svg).toBeNull();
    });
    
    it('should handle SVG with attributes', () => {
      const html = '<svg width="200" height="150" viewBox="0 0 200 150"></svg>';
      const svg = exporter.extractSVG(html);
      
      expect(svg).toContain('width="200"');
      expect(svg).toContain('viewBox');
    });
  });
  
  describe('Metadata Injection', () => {
    it('should add metadata element to SVG', () => {
      const svg = '<svg><circle r="10"/></svg>';
      const metadata = { title: 'Test Artifact', description: 'Test description' };
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('<metadata>');
      expect(result).toContain('</metadata>');
    });
    
    it('should include RDF namespace', () => {
      const svg = '<svg></svg>';
      const metadata = { title: 'Test' };
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('xmlns:rdf=');
      expect(result).toContain('xmlns:dc=');
    });
    
    it('should include artifact title', () => {
      const svg = '<svg></svg>';
      const metadata = { title: 'Signal Map Artifact' };
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('<dc:title>Signal Map Artifact</dc:title>');
    });
    
    it('should include artifact description', () => {
      const svg = '<svg></svg>';
      const metadata = { description: 'Custom description' };
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('<dc:description>Custom description</dc:description>');
    });
    
    it('should include creator information', () => {
      const svg = '<svg></svg>';
      const metadata = { title: 'Test' };
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('<dc:creator>CTS MCP Server v3.2.0</dc:creator>');
    });
    
    it('should include timestamp', () => {
      const svg = '<svg></svg>';
      const metadata = { title: 'Test' };
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('<dc:date>');
      expect(result).toMatch(/<dc:date>\d{4}-\d{2}-\d{2}T/);
    });
    
    it('should escape XML special characters in title', () => {
      const svg = '<svg></svg>';
      const metadata = { title: 'Test <>&"\' Artifact' };
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('&lt;');
      expect(result).toContain('&gt;');
      expect(result).toContain('&amp;');
      expect(result).toContain('&quot;');
      expect(result).toContain('&apos;');
    });
    
    it('should use default title if not provided', () => {
      const svg = '<svg></svg>';
      const metadata = {};
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('<dc:title>CTS Artifact</dc:title>');
    });
    
    it('should use default description if not provided', () => {
      const svg = '<svg></svg>';
      const metadata = {};
      
      const result = exporter.addMetadata(svg, metadata);
      
      expect(result).toContain('<dc:description>Generated by CTS MCP Server</dc:description>');
    });
  });
  
  describe('ViewBox Optimization', () => {
    it('should not modify existing viewBox', () => {
      const svg = '<svg viewBox="0 0 100 100"></svg>';
      const result = exporter.optimizeViewBox(svg);
      
      expect(result).toBe(svg);
    });
    
    it('should add viewBox from width and height', () => {
      const svg = '<svg width="200" height="150"></svg>';
      const result = exporter.optimizeViewBox(svg);
      
      expect(result).toContain('viewBox="0 0 200 150"');
    });
    
    it('should preserve existing attributes', () => {
      const svg = '<svg width="100" height="100" id="graph"></svg>';
      const result = exporter.optimizeViewBox(svg);
      
      expect(result).toContain('width="100"');
      expect(result).toContain('height="100"');
      expect(result).toContain('id="graph"');
    });
    
    it('should not add viewBox if dimensions missing', () => {
      const svg = '<svg id="graph"></svg>';
      const result = exporter.optimizeViewBox(svg);
      
      expect(result).toBe(svg);
    });
  });
  
  describe('Namespace Handling', () => {
    it('should not modify existing namespace', () => {
      const svg = '<svg xmlns="http://www.w3.org/2000/svg"></svg>';
      const result = exporter.ensureNamespace(svg);
      
      expect(result).toBe(svg);
    });
    
    it('should add namespace if missing', () => {
      const svg = '<svg width="100" height="100"></svg>';
      const result = exporter.ensureNamespace(svg);
      
      expect(result).toContain('xmlns="http://www.w3.org/2000/svg"');
    });
  });
  
  describe('Full Processing', () => {
    it('should apply all optimizations', () => {
      const svg = '<svg width="100" height="100"><circle r="10"/></svg>';
      const metadata = { title: 'Test Artifact' };
      
      const result = exporter.processSVGForExport(svg, metadata);
      
      expect(result).toContain('xmlns="http://www.w3.org/2000/svg"');
      expect(result).toContain('viewBox="0 0 100 100"');
      expect(result).toContain('<metadata>');
      expect(result).toContain('<dc:title>Test Artifact</dc:title>');
    });
    
    it('should preserve SVG content', () => {
      const svg = '<svg><g><circle r="10"/><rect width="20"/></g></svg>';
      const metadata = { title: 'Test' };
      
      const result = exporter.processSVGForExport(svg, metadata);
      
      expect(result).toContain('<circle r="10"/>');
      expect(result).toContain('<rect width="20"/>');
    });
  });
  
  describe('Extract and Process', () => {
    it('should extract and process SVG in one call', () => {
      const html = '<html><body><svg width="100" height="100"></svg></body></html>';
      const metadata = { title: 'Combined Test' };
      
      const result = exporter.extractAndProcess(html, metadata);
      
      expect(result).not.toBeNull();
      expect(result).toContain('xmlns="http://www.w3.org/2000/svg"');
      expect(result).toContain('viewBox="0 0 100 100"');
      expect(result).toContain('<dc:title>Combined Test</dc:title>');
    });
    
    it('should return null if no SVG in HTML', () => {
      const html = '<html><body><div>No SVG</div></body></html>';
      const metadata = { title: 'Test' };
      
      const result = exporter.extractAndProcess(html, metadata);
      
      expect(result).toBeNull();
    });
  });
});
